---
# Home Assistant can get information from various devices. These can be used,
# for example, to track the location of your mobile phone.
#
device_tracker: !include_dir_list ../entities/device_trackers
