---
# This contain all helper inputs.
# They can for example be used to disable or enable certain automations.
#
input_boolean: !include_dir_merge_named ../entities/input_booleans
input_datetime:
input_number:
input_select:
input_text:
counter:
timer:
