---
# The http component serves all files and data required for the
# Home Assistant frontend.
# TLS is used over a nginx reverse proxy.
#
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret nginx_internal_ip
