---
# The Media Source integration platform allows integrations to expose media 
#for use inside Home Assistant through the Media Browser panel or through 
# supported media players like Google Cast. 
media_source:
