---
# My Home Assistant allows the documentation to link you to specific pages in your Home Assistant instance. See the My Home Assistant FAQ for more information.
# see https://www.home-assistant.io/integrations/my/
#
my:
