---
# The recorder component is storing details in a database which
# then are handled by the history component.
#
recorder:
  db_url: !secret recorder_url
  purge_keep_days: 14
  exclude:
    domains:
      - weblink
    entities:
      - sensor.augsburg_hauptbahnhof_to_munchen_pasing
