---
# The speedtestdotnet integration uses the Speedtest.net
# web service to measure network bandwidth performance.
#
#
speedtestdotnet:
  # The speedtest is scheduled over node-red
  manual: true
  server_id: 24495




