  
---
# The updater component will check daily for new releases.
# It will show a badge in the frontend if a new version is found.
#
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#
updater:
  reporting: true

  # Allow some data of used components
  # To look up what is sent: https://www.home-assistant.io/docs/backend/updater/
  include_used_components: true