esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

<<: !include common.yaml

switch:
  - platform: restart
    name: Steckdose ${human_devicename} Neustart

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO4
      inverted: True
  - platform: gpio
    pin: GPIO12
    id: relay

status_led:
  pin: 
    number: GPIO5
    inverted: True
