wifi: 
  ssid: !secret esphome_wifi_name
  password: !secret esphome_wifi_pass
  domain: .fritz.box
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esphome_wifi_fallback_name
    password: !secret esphome_wifi_fallback_pass  
    
mqtt: 
  broker: p-assist.fritz.box
  username: !secret esphome_mqtt_user
  password: !secret esphome_mqtt_pass
  discovery: True

captive_portal:

logger:

ota:

time:
  - platform: sntp
    id: sntp_time
    servers:
      - fritz.box 

sensor:
  - platform: wifi_signal
    name: "${human_devicename} Signalstärke"

switch:
  - platform: restart
    name: ${human_devicename} Neustart
