<<: !include wifi.yaml 
    
mqtt: 
  broker: p-assist.fritz.box
  username: !secret esphome_mqtt_user
  password: !secret esphome_mqtt_pass
  discovery: True

captive_portal:

logger:

ota:
  
sensor:
  - platform: wifi_signal
    name: "${human_devicename} Signalstärke"

switch:
  - platform: restart
    name: ${human_devicename} Neustart
