<<: !include wifi.yaml 

captive_portal:

logger:

ota:
  
sensor:
  - platform: wifi_signal
    name: "${human_devicename} Signalstärke"

switch:
  - platform: restart
    name: ${human_devicename} Neustart
