wifi: 
  ssid: !secret esphome_wifi_name
  password: !secret esphome_wifi_pass
  domain: .fritz.box
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esphome_wifi_fallback_name
    password: !secret esphome_wifi_fallback_pass  

time:
  - platform: sntp
    id: sntp_time
    servers:
      - fritz.box 