id: livingroom_fan_on
alias: Wohnzimmer Lüfter On
description: ''
trigger:
- platform: template
  value_template: "{{states.sensor.wohnzimmer_luefter_power.state | float > 20}}"
condition: []
action:
- data:
    entity_id: input_boolean.livingroom_fan_power
  service: input_boolean.turn_on