id: livingroom_fan_off
alias: Wohnzimmer Lüfter Off
description: ''
trigger:
- platform: template
  value_template: "{{states.sensor.wohnzimmer_luefter_power.state | float < 10}}"
condition: []
action:
- data:
    entity_id: input_boolean.livingroom_fan_power
  service: input_boolean.turn_off