---
# This starts the syncthing addon for some time to allow a backup.
#
backup_time:
  alias: Start Syncthing for some time
  sequence:
  - service: hassio.addon_start
    data:
      addon: 53caca22_syncthing
  - delay: 00:30
  - service: hassio.addon_stop
    data:
      addon: 53caca22_syncthing