---
# One of the scripts to control my living room fan.
#
towerfan_oscillate:
  sequence:
    - service: broadlink.send
      data:
        host: !secret ip_rm_mini
        packet: JgCCACoNKwwPKCsMKg0PKA8oKg0OKA8oDygPAAEEKA8oDw0qKA8oDg0qDSopDg0qDSoOKQ0AAQYoDygODSopDikODSoNKigPDSoOKQ0qDQABAiwOKQ4NKigPKA8NKg0qKA8NKg4oDygPAAEEKg0qDQ8oKg0qDQ4pDigpDg0qDSoNKg0ADQUAAAAAAAA=
