---
# One of the scripts to control my living room fan.
#
towerfan_power_on:
  sequence:
    - condition: state
      entity_id: input_boolean.livingroom_fan_power
      state: 'off'
    - service: switch.turn_on
      data:
        entity_id: switch.shelly_plug_s_fan_livingroom_relay_0
    - service: broadlink.send
      data:
        host: !secret ip_rm_mini
        packet: JgD6ABMvFi4NMhIABpQQMxMtEy4SAAaUETARMRIwEgAGkxIwEy8SLxMABpMQMRIvEjATAAaSEy8RMBIwEwAGkxExEi8SLxMABpQSNgo0DTASAAaUEjASMBMuEwAGkxMvETARMRIABpMSMBMvETATAAaTEjARIykNKg0NKygOKQ4NKg0qDSoNKg0qDSoo6ikOKA8NKigPKA8NKg4oDSoNKg0qDSop6igPKA8NJC4OKg4MKg0qDikNKg0qDSoq6SoNKQ4OKCoNKg0OKQ8oDygPKA8oDygrAAGLEi8SMBIwFAAGlww4CjARMg0ABpcPMxI2DDAOAAblCgAHlwwADQUAAAAAAAAAAAAAAAAAAA==
    - service: broadlink.send
      data:
        host: !secret ip_rm_mini
        packet: JgCCACoNKwwPKCsMKg0PKA8oKg0OKA8oDygPAAEEKA8oDw0qKA8oDg0qDSopDg0qDSoOKQ0AAQYoDygODSopDikODSoNKigPDSoOKQ0qDQABAiwOKQ4NKigPKA8NKg0qKA8NKg4oDygPAAEEKg0qDQ8oKg0qDQ4pDigpDg0qDSoNKg0ADQUAAAAAAAA=
