---
# The Air quality sensor of the living room
#
name: Wohnzimmer
sources:
  temperature: sensor.ble_temperature_wohnzimmer
  humidity: sensor.ble_humidity_wohnzimmer
  #co2: sensor.bettbeleuchtung_eco2
  #tvoc: sensor.bettbeleuchtung_tvoc
sensors:
  - iaq_level
