---
# The Air quality sensor of the living room
#
name: Wohnzimmer
sources:
  temperature: sensor.ble_temperature_wohnzimmer
  humidity: sensor.ble_humidity_wohnzimmer
  co2: sensor.frischluft_co2
sensors:
  - iaq_level
