---
# The Air quality sensor of the sleeping room
#
name: Schlafzimmer
sources:
  temperature: sensor.ble_temperature_schlafzimmer
  humidity: sensor.ble_humidity_schlafzimmer
  co2: sensor.schreibtisch_monitor_co2
sensors:
  - iaq_level
