---
# The Air quality sensor of the sleeping room
#
name: Schlafzimmer
sources:
  temperature: sensor.ble_temperature_schlafzimmer
  humidity: sensor.ble_humidity_schlafzimmer
  co2: sensor.schreibtisch_monitor_eco2
  tvoc: sensor.schreibtisch_monitor_fluchtige_organische_verbindungen
sensors:
  - iaq_level
