---
# The Google Text-to-Speech platform use Google Text-to-Speech engine to
# read a text with a natural sounding voice(s).
#
platform: google_translate
language: 'de'
cache: true

# Caching location to tmp
cache_dir: /tmp/tts

# Time to hold (in seconds) the voice data inside memory for fast play
# on a media player.
time_memory: 300