---
# This is just a bootstrap for the configuration.
# I structured this config after the example from FRENCK.
#
# He's explaining it here: https://www.youtube.com/watch?v=lndeybw21PY
#
homeassistant:
  # All integration at the integration folder will be loaded with that.
  packages: !include_dir_named integrations
  
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include_dir_merge_named ../customizations/entities
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url

