---
# This is just a bootstrap for the configuration.
# I structured this config after the example from FRENCK.
#
# He's explaining it here: https://www.youtube.com/watch?v=lndeybw21PY
#
homeassistant:
  # All integration at the integration folder will be loaded with that.
  packages: !include_dir_named integrations
  
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include_dir_merge_named customizations/entities
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - !secret ip_markus_android
        - !secret ip_markus_laptop_lan
        - !secret ip_markus_laptop_wifi
        - !secret ip_markus_desktop
        - !secret ip_work_laptop_lan
        - !secret ip_work_laptop_wifi

