# api keys
dark_sky_api_key: ""
openweathermap_api_key: ""
telegram_markus_id: ""
telegram_bot_key: ""
github_api_token: ""
habitica_api_user: ""
habitica_api_key: ""

# Local ips
ip_home_range: ""
ip_markus_android: ""
ip_markus_watch: ""
ip_sony_tv: ""
ip_markus_laptop_wifi: ""
ip_markus_desktop: ""
ip_rm_mini: ""
ip_markus_laptop_lan: ""
ip_markus_switch: ""
ip_work_laptop_wifi: ""
ip_work_laptop_lan: ""

# Mac addresses
mac_rm_mini: ""
mac_eq3_livingroom: ""

# domains
cloud_domain: ""
nas_domain: ""
homeassistant_domain: ""
homeassistant_external_url: ""
homeassistant_internal_url: ""

# connection stuff
p-radio_desc_url: ""
roborock_mqtt_url: ""

# home zone
home_latitude: ""
home_longitude: ""
home_elevation: ""

# MariaDB
recorder_url: ""
maria_user: ""
maria_pass: ""

# Node Red
node_red_credential_secret: ""

# InfluxDB
influxDB_password: ""

# Samba share
samba_user: ""
samba_pass: ""

# ESPHome secrets
esphome_wifi_name: ""
esphome_wifi_pass: ""
esphome_wifi_fallback_name: ""
esphome_wifi_fallback_pass: ""
esphome_mqtt_user: ""
esphome_mqtt_pass: ""

# MQTT secrets
debug_mqtt_user: ""
debug_mqtt_pass: ""
roborock_mqtt_user: ""
roborock_mqtt_password: ""
shelly_plug_mqtt_user: ""
shelly_plug_mqtt_password: ""
node-red_mqtt_user: ""
node-red_mqtt_password: ""
p-dice_mqtt_user: ""
p-dice_mqtt_password: ""
rhasspy_mqtt_user: ""
rhasspy_mqtt_password: ""

# mitemp secrets
mac_mitemp_balcony: ""
mac_mitemp_sleeping: ""
mac_mitemp_bath: ""
mitemp_encryptors: ""
  'A4: ""
  'A4: ""
  'A4: ""

# twitch
twitch_client_id: ""
twitch_oauth_token: ""

# bring shopping list
bring_username: ""
bring_password: ""
bring_homelist_id: ""
