---
# The circadian switch for the living room showcase
#
platform: circadian_lighting
name: Circadian Lighting Vitrine
min_brightness: 30
lights_rgb:
  - light.vitrine_leds
disable_entity: input_boolean.vitrine_leds_animating
disable_state: "on"
