---
# The circadian switch for the working desk lamps
#
platform: circadian_lighting
name: Circadian Lighting Schreibtisch
lights_rgb:
  - light.schreibtischlampe_schreibtisch
  - light.schreibtischlampe_gesicht
disable_brightness_adjust: true
disable_entity: input_boolean.schreibtisch_animating
disable_state: "on"
