#
# This curls the Valetudo software of my roborock vacumn and checks if its still there. It tends to reset itself lately!
#
platform: command_line
name: Valetudo aktiv
command: response=$(curl -LIk http://dusty.fritz.box -o /dev/null -w '%{http_code}\n' -s); test "$response" -ge 200 && echo "on" || echo "off"
scan_interval: 600
payload_on: "on"
payload_off: "off"
device_class: connectivity
