---
# The workday binary sensor indicates, whether the current day is a workday or not.
# I use it to let some automations (vacuum cleaner) only run on non-holiday and non-sundays
#
platform: workday
name: Workdays and Saturday
country: DE
province: BY
workdays:
  - mon
  - tue
  - wed
  - thu
  - fri
  - sat
excludes:
  - sun
  - holiday
