---
# This should make my ir fan in the living room more controlable over the ui.
#
# https://github.com/smartHomeHub/SmartIR
#
platform: smartir
name: Wohnzimmer Lüfter
unique_id: wohnzimmer_luefter
device_code: 1140
controller_data: !secret ip_rm_mini
