---
# Get donor statistics of folding@home.
#
platform: rest
resource: https://api2.foldingathome.org/user/Poeschl
name: Folding at Home
value_template: '{{ value_json.score }}'
scan_interval: 1800
unit_of_measurement: credits
json_attributes:
  - last
  - rank
  - wus
  - name
