---
#
# Pre-Processing the speed values of the fritzbox_netmonitor sensor to show them directly in the ui.
#
platform: template
sensors:
  fritzbox_download:
    friendly_name: "Fritzbox Download"
    unit_of_measurement: 'Mbit/s'
    value_template: "{{ [(state_attr('sensor.fritz_netmonitor', 'transmission_rate_down') * 8.0) / 1024 / 1024, 0] | max | round(2) }}"
  fritzbox_upload:
    friendly_name: "Fritzbox Upload"
    unit_of_measurement: 'Mbit/s'
    value_template: "{{ [(state_attr('sensor.fritz_netmonitor', 'transmission_rate_up') * 8.0) / 1024 / 1024, 0] | max | round(2) }}"
