---
# The config for the Xiaomi LYWSD03MMC sensors.
# Uses the custom integration: https://github.com/custom-components/sensor.mitemp_bt
#
platform: mitemp_bt
batt_entities: true
devices:
  - name: Balkon
    mac: !secret mac_mitemp_balcony
    encryption_key: !secret key_mitemp_balcony
  - name: Schlafzimmer
    mac: !secret mac_mitemp_sleeping
    encryption_key: !secret key_mitemp_sleeping
  - name: Bad
    mac: !secret mac_mitemp_bath
    encryption_key: !secret key_mitemp_bath
  - name: Wohnzimmer
    mac: !secret mac_mitemp_livingroom
    encryption_key: !secret key_mitemp_livingroom
