substitutions:
  devicename: bad_luefter
  human_devicename: Shelly Bad

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  build_path: /tmp/build/${devicename}

<<: !include includes/common.yaml

<<: !include includes/mqtt.yaml

binary_sensor:
  - platform: gpio
    id: input_switch
    pin: GPIO5
    on_press:
      - fan.turn_on: bath_fan
    on_release:
      - delay: 10min
      - fan.turn_off: bath_fan
    on_double_click:
      - fan.turn_off: bath_fan

output:
  - platform: gpio
    pin: GPIO4
    id: relay

fan:
  - platform: binary
    id: bath_fan
    output: relay
    name: "Bad Lüfter"

