esphome:
  name: multimedia_steckdose
  platform: ESP8266
  board: esp01_1m

<<: !include includes/common.yaml

binary_sensor:
  - platform: gpio
    id: input_switch
    pin:
      number: GPIO5
      inverted: True
    on_state:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Multimedia Steckdose"
    pin: GPIO4
    id: relay
  - platform: restart
    name: "Multimedia Steckdose Neustart"

