substitutions:
  devicename: schlafzimmer_bett
  human_devicename: Bettbeleuchtung

esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2

<<: !include includes/common.yaml

light:
  - platform: fastled_clockless
    id: led
    rgb_order: GRB
    chipset: WS2812B
    pin: D1
    num_leds: 156
    name: "Bettbeleuchtung LEDs"
    effects:
      - addressable_rainbow:    
      - addressable_scan:
          name: Scan
          scan_width: 8
          move_interval: 50ms
      - addressable_color_wipe:
          name: White color
          colors:
            - red: 100%
              green: 86%
              blue: 71%
              num_leds: 1
          add_led_interval: 50ms
      - addressable_twinkle:
          twinkle_probability: 15%
          progress_interval: 15ms
      - lambda:
           name: Breathing
           update_interval: 2s
           lambda: |-
            static int state = 0;
            static int color = 1;
            auto call = id(led).turn_on();
            call.set_transition_length(3000);
            if (state == 0) {
              call.set_brightness(1.0);
            } else if (state == 1) {
              call.set_brightness(0.01);
            }
            call.perform();
            state ++;
            if (state == 2) {
              state = 0;
            }
            
binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: true
    name: Bett Taste rechts
    internal: true
    on_click:
      - light.toggle: led
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: true
    name: Bett Taste mitte
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
      inverted: true
    name: Bett Taste links
