substitutions:
  devicename: schreibtischlampe
  human_devicename: Schreibtischlampe

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini
  build_path: /tmp/build/${devicename}

<<: !include includes/common.yaml

<<: !include includes/native_api.yaml
      
i2c:
  sda: D7
  scl: D6
  # scan: True
  
sensor:
  - platform: homeassistant
    id: temp
    internal: true
    entity_id: sensor.mi_temperature_schlafzimmer
  - platform: homeassistant
    id: humidity
    internal: true
    entity_id: sensor.mi_humidity_schlafzimmer
  - platform: ccs811
    eco2:
      name: "${human_devicename} eCO2"
      filters:
        - lambda: |-
            float MAX_VALUE = 8000.0;
            float MIN_VALUE = 100.0;
            if (MIN_VALUE <= x && x <= MAX_VALUE) return x;
            else return {};
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3
            send_first_at: 1
    tvoc:
      name: "${human_devicename} TVOC"
      filters:
        - lambda: |-
            float MAX_VALUE = 2000.0;
            float MIN_VALUE = 0.1;
            if (MIN_VALUE <= x && x <= MAX_VALUE) return x;
            else return {};
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3
            send_first_at: 1
    address: 0x5A
    update_interval: 60s
    # baseline: 0xAEC3
    temperature: temp
    humidity: humidity
  - platform: wifi_signal
    name: "${human_devicename} Signalstärke"

wled:

light:
  - platform: fastled_clockless
    id: leds
    rgb_order: GRB
    chipset: WS2812B
    pin: D8
    num_leds: 32
    name: "${human_devicename} Alles"
    internal: true

  - platform: partition
    name: "${human_devicename} Schreibtisch"
    segments:
      - id: leds
        from: 0
        to: 15
    effects:
      - addressable_rainbow:
      - wled:
      - addressable_scan:
          scan_width: 3
          move_interval: 50ms

  - platform: partition
    name: "${human_devicename} Gesicht"
    segments:
      - id: leds
        from: 16
        to: 31
    effects:
      - addressable_rainbow:
      - addressable_scan:
          scan_width: 3
          move_interval: 50ms

