substitutions:
  devicename: schreibtisch_monitor
  human_devicename: 'Schreibtisch Monitor'

esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2
  build_path: /tmp/build/${devicename}

<<: !include includes/common.yaml

<<: !include includes/mqtt.yaml

wled:

light:
  - platform: fastled_clockless
    id: led
    rgb_order: GRB
    chipset: WS2812B
    pin: D1
    num_leds: 160
    name: "Monitorbeleuchtung"
    effects:
      - addressable_rainbow:  
      - wled:
      - addressable_scan:
          name: Scan
          scan_width: 8
          move_interval: 20ms
