esphome:
  name: test_streamlight
  platform: ESP32
  board: nodemcu-32s

<<: !include includes/common.yaml

light:
  - platform: fastled_clockless
    id: led
    rgb_order: GRB
    chipset: WS2812B
    pin: 12
    num_leds: 14
    name: "Test Streamlight"
