---
# This automation sends out the announcement command for all shelly devices which are connected to the mqtt borker.
# The result is parsed in the shelly_discovery automation.
#
id: shellies_announce
alias: 'Shellies Announce'
trigger:
  - platform: homeassistant
    event: start
action:
  service: mqtt.publish
  data:
    topic: shellies/command
    payload: announce