---
#
# This directly scans the network for devices by using Nmap. 
#
# Here I only ping known devices to reduce the overall load on the network. And also don't track other devices.
#
platform: nmap_tracker
hosts:
  - !secret ip_markus_android
  - !secret ip_markus_watch
  - !secret ip_markus_desktop
  - !secret ip_markus_laptop_wifi
  - !secret ip_markus_laptop_lan
  - !secret ip_work_laptop_wifi
  - !secret ip_work_laptop_lan
consider_home: 0:04
home_interval: 4
interval_seconds: 15
scan_options: " --privileged -sP "
new_device_defaults:
  track_new_devices: true
